name: OWASP ZAP Scan
on:
  push:
    branches:
      - main
jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://mlshoppreprod.mlhuillier.com/jewelryback/Account/OrderDetails?OrderNumber=MLMDKEXTVBL&OrderId=O20241007135949882172'
          rules_file_name: '.github/workflows/.zap-rules.yaml'   # Correct input for custom rules
          cmd_options: '-J report_json.json -w report_md.md -r report_html.html'   # Additional ZAP options
          

