name: ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run OWASP ZAP Baseline Scan
      run: |
        # Pull the OWASP ZAP Docker image
        docker pull zaproxy/zap-stable
        
        # Start ZAP in daemon mode
        docker run -d --name zap -u zap -p 8080:8080 zaproxy/zap-stable zap-baseline.py -t https://google.com
        
        # Run the baseline scan on the application URL and store the results in a file
        docker exec zap zap-baseline.py -t http://google.com -g gen.conf -r reports/zap_report.html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: reports/zap_report.html

    - name: Fail the build if high-severity vulnerabilities are found
      run: |
        if grep -q "High" reports/zap_report.html; then
          echo "High severity vulnerabilities found, failing the build!"
          exit 1
        fi
