name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Ensure correct permissions for the workspace directory
    - name: Set permissions for workspace
      run: |
        # Grant read-write permissions to the workspace directory
        sudo chmod -R 777 ${{ github.workspace }}

    # Step 3: Set up OWASP ZAP using the Docker container
    - name: Set up OWASP ZAP
      run: |
        # Ensure we are pulling the latest version of the ZAP image
        docker pull zaproxy/zap-stable:latest

    # Step 4: Run ZAP Scan against your application
    - name: Run ZAP Scan
      run: |
        # Mount the workspace directory and generate the report at a known location
        docker run --rm -v ${{ github.workspace }}:/zap/wrk zaproxy/zap-stable:latest zap-baseline.py -t https://igsglobal.com/our-solutions -r /zap/wrk/zap-report.html

    # Step 5: Upload the ZAP scan report as an artifact
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: ${{ github.workspace }}/zap-report.html
