name: OWASP ZAP Scan
on:
  push:
    branches:
      - main
jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
         target: 'https://mlshoppreprod.mlhuillier.com/jewelryback/Account/OrderDetails?OrderNumber=MLMDKEXTVBL&OrderId=O20241007135949882172'
         rules-file-path: '.zap-rules.yaml'
         zap-settings-file-path: '.zap-settings'
      - name: Filter False Positives
        run: |
          echo "Filtering False Positives"
          python filter_false_positives.py
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP-Report
