name: ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run OWASP ZAP Baseline Scan
      run: |
        # Pull the OWASP ZAP Docker image
        docker pull zaproxy/zap-stable:2.15.0
        
        # Create a directory to store ZAP reports and configurations
        mkdir -p $PWD/zap-reports

        # Start ZAP in daemon mode with volume mounting
        docker run -d --name zap -u zap -p 8080:8080 -v $PWD/zap-reports:/zap/reports zaproxy/zap-stable
        
        # Wait for a few seconds to ensure ZAP is fully started and ready to scan
        sleep 15
        
        # Check if the container is running, log its status for debugging
        docker ps
        docker logs zap

        # Run the baseline scan on the application URL (replace this with your app URL) and store the results
        docker exec zap zap-baseline.py -t https://google.com -g gen.conf -r /zap/reports/zap_report.html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap-reports/zap_report.html

    - name: Fail the build if high-severity vulnerabilities are found
      run: |
        # Check if "High" severity vulnerabilities are in the report
        if grep -q "High" zap-reports/zap_report.html; then
          echo "High severity vulnerabilities found, failing the build!"
          exit 1
        fi
