name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up directories and fix permissions
      - name: Set up directories and fix permissions
        run: |
          # Create necessary directories if they do not exist
          mkdir -p $GITHUB_WORKSPACE/zap-reports
          mkdir -p $GITHUB_WORKSPACE/zap-wrk
          
          # Ensure the directories have proper read-write permissions
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE/zap-reports
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE/zap-wrk

          # Set read-write permissions on the directories
          sudo chmod -R 777 $GITHUB_WORKSPACE/zap-reports
          sudo chmod -R 777 $GITHUB_WORKSPACE/zap-wrk

      # Step 3: Run ZAP scan with correct permissions and mount volumes
      - name: Run ZAP Scan
        run: |
          docker run -t \
            -v $GITHUB_WORKSPACE/zap-reports:/zap/reports:rw \
            -v $GITHUB_WORKSPACE/zap-wrk:/zap/wrk:rw \
            --user $(id -u):$(id -g) \
            zaproxy/zap-stable:2.15.0 zap-baseline.py -t https://google.com -r /zap/reports/zap-report.html

      # Step 4: Upload the ZAP scan report as an artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: $GITHUB_WORKSPACE/zap-reports/zap-report.html

