name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create directories
        run: |
          mkdir -p $GITHUB_WORKSPACE/zap-reports
          mkdir -p $GITHUB_WORKSPACE/zap-wrk

      - name: Run ZAP Scan
        run: |
          docker run -t \
            -v $GITHUB_WORKSPACE/zap-reports:/zap/reports \
            -v $GITHUB_WORKSPACE/zap-wrk:/zap/wrk:rw \
            zaproxy/zap-stable:2.15.0 zap-baseline.py -t https://google.com -r /zap/reports/zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: $GITHUB_WORKSPACE/zap-reports/zap-report.html
