name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Configuration Files
        run: |
          ls -l .github/workflows/.zap-settings
          ls -l .github/workflows/.zap-rules.yaml

      - name: Set Permissions
        run: chmod 666 .github/workflows/.zap-settings .github/workflows/.zap-rules.yaml

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          rules-file-path: '.github/workflows/.zap-rules.yaml'
          zap-settings-file-path: '.github/workflows/.zap-settings'
          target: 'https://mlshoppreprod.mlhuillier.com/jewelryback/Account/OrderDetails?OrderNumber=MLMDKEXTVBL&OrderId=O20241007135949882172'
   
     
      - name: Filter False Positives
        run: python .github/workflows/filter_false_positives.py
